### ISSUE TITLE
Incorrect docs for `modals.closeModals()`

### ISSUE THREAD

**Issue by gribelu** [cferdinandi/modals#20]
Hello,

The docs state that the first parameter for `closeModals()` is the options object but it's actually the target so in order to pass the options object it needs to be called like this: `modals.closeModals(null, options)`

Thanks for the work!

**Comment by cferdinandi** [comment]
Good catch! Updated the way the script works and that one slipped through the cracks. Will update.

**Comment by cferdinandi** [comment]
Fixed

**Comment by cferdinandi** [comment]
https://github.com/cferdinandi/modals/pull/22
