### ISSUE TITLE
[Question]: Interested in converting Bootstrap 3 Plugins to Plain JS ?

### ISSUE THREAD

**Issue by thednp** [cferdinandi/modals#21]
Hi. I know you don't like me :)
(you may not like BS)

BUT gonna ask anyways.

I see you have plenty examples working fine with IE9+ you have already developed. Most of them cover the most of the needs and I was thinking...

Would you be interested in teaming up to convert all BS plugins to PLAIN JS? 
This would create more opportunities for us and many more developers to drop jQuery and develop better performance apps for the web :)

**Comment by cferdinandi** [comment]
Umm... why don't I like you?

But to answer your question: I've already created native JS alternatives to all of the Bootstrap plugins I feel are worth converting or have had a need for in my freelance life, and I have about zero time to expand my open source projects at the moment.

Interesting idea, but I'm going to have to respectfully pass at this time. Thanks!

**Comment by thednp** [comment]
Thanks for your time :)
