### ISSUE TITLE
Dist Sass

### ISSUE THREAD

**Issue by klombomb** [cferdinandi/modals#41]
Have you thought about adding Sass for the dist to?
I would be more than willing to help you create something!

**Comment by cferdinandi** [comment]
Why? Sass is a not a distribution appropriate format since browser's cannot parse it. It's used in production to create distribution files.

Anyone who wants to use Sass has access to the `src` directory. Is there a compelling reason to do anything different?

**Comment by klombomb** [comment]
Indeed you are correct, my bad.
