### ISSUE TITLE
Close called as soon as openModal is called manually with dynamic modal.

### ISSUE THREAD

**Issue by samhibberd** [cferdinandi/modals#66]
Hi @cferdinandi,

First off, I fully appreciate that this is likely an issue my end, but I wanted to see if I am missing anything really obvious.

`modals.init({my: options})` is called on page load.

I am then loading modal html in on request via ajax, on the first request the modal is loaded into to the dom and then `modals.openModal(null, '#idOfNewElement')` is called, this works fine.

On all modal requests I run a check to see if '#idOfNewElement' exists in the dom and if it has previously been loaded I then call `modals.openModal(null, '#idOfNewElement')` and don't load it in again.

This is where it falls down, it looks as if the classes get added and then removed, which ties up with the both `callbackOpen` and then `callbackClose` being called.

I just cant work out why or find any errors anywhere :(

And oddly if I call `modals.openModal(null, '#idOfNewElement')` from the Chrome console it fires ok.

Any ideas would be really appreciated!

Sam

**Comment by cferdinandi** [comment]
Can you provide me with a demo link? JSFiddle or CodePen preferred, though a link to a GitHub repo works, too.

Thanks!

**Comment by samhibberd** [comment]
I can provide you an access link to our staging environment, Ive dropped a mail to your Go Make Things address.

Thanks,

Sam

**Comment by cferdinandi** [comment]
@samhibberd Just wanted to let you know it has **not** arrived.

**Comment by samhibberd** [comment]
Sorry I've resent. Received ok? S

**Comment by samhibberd** [comment]
Hi Chris, was wondering if you have any ideas on this one? Hopefully my email arrived ok?

**Comment by cferdinandi** [comment]
Email arrived. Wasn't sure what I was supposed to be looking at. Responded via email with details.

**Comment by cferdinandi** [comment]
Moved to email.

**Comment by cferdinandi** [comment]
Bringing this back full circle, I would...

1. Init modals as usual: `modals.init()`.
2. Use a different selector than `[data-modal]` for the modal toggle, but **don't** pass that in as the officially selector into Modals. For example, something like `[data-modal-toggle]`.
3. I'd use this event listener to run my async load *only* if the modal isn't already in the DOM:
    
	window.addEventListener('click', function asyncModals(event) {

		// Only run if a modal toggle was clicked
		var toggle = event.target.closest('[data-modal-toggle]');
		if (!toggle) return;

		// Prevent default link behavior
		event.preventDefault();

		// If modal is already in the DOM
		if (document.querySelector(toggle.hash)) {
			modals.openModal(toggle, toggle.hash);
			return;
		}

		// Otherwise, load it async using your preferred async method
		// NOTE: You need to write this part

		// On success, open it
		// modals.openModal(toggle, toggle.hash)

	}, false);

Why this approach? By running  `modals.init()`, you can take advantage of the built in close functionality. BUT, by using a different selector, you prevent the script from trying to open the modal twice.

You effectively want to bypass the normal opening process and run your own.
